#ifndef CANDY_ERROR_H_
#define CANDY_ERROR_H_

#define CANDY_HAUSNUMERO 156384712

#define CANDY_EUNSATRT (CANDY_HAUSNUMERO+1)

#define CANDY_EFULL (CANDY_HAUSNUMERO+2)

#define CANDY_ENOTAIO (CANDY_HAUSNUMERO+3)

#endif
