#ifndef CANDY_ERROR_H_
#define CANDY_ERROR_H_

#if defined CANDY_HAVE_WINDOWS
	#define CANDY_GET_ERRNO GetLastError()
	#define CANDY_EAGAIN WSAEWOULDBLOCK
	#define CANDY_EINTR WSAEINTR
	#define CANDY_ETIMEOUT WSAETIMEDOUT
	#define CANDY_EINPROGRESS WSAEINPROGRESS
#else
	#include <errno.h>
	#define CANDY_GET_ERRNO errno
	#define CANDY_EAGAIN EAGAIN
	#define CANDY_EINTR EINTR
	#define CANDY_ETIMEOUT ETIMEDOUT
	#define CANDY_EINPROGRESS EINPROGRESS
#endif
#endif
